# travis config
language: r

cache: packages

os:
  - linux

r_github_packages:
  - jakobbossek/ecr2
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
    on_success: change
    on_failure: always
