# travis config
language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux

r_github_packages:
  - jakobbossek/ecr2
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
    on_success: change
    on_failure: always
